### ISSUE TITLE
Error if multiple versioning strategies used in a request?

### ISSUE THREAD

**Issue by johnrees** [bploetz/versionist#72] opened 2015-09-30 16:23 UTC
I'll submit a failing spec for this if other people have experienced it?

If I have this in my routes -

```
api_version(module: "V01", path: {value: "v0.1"}, header: {name: "Accept", value: "application/vnd.url.com; version=0.1"}, default: true, defaults: { format: :json }) do
  resources :things
end
```

I can access these URLs

`url.com/v0.1/things/1`
`url.com/things/1 { Accept: "application/vnd.url.com; version=0.1" }`

but if I try to use both strategies and submit the header with the path

`url.com/v0.1/things/1 { Accept: "application/vnd.url.com; version=0.1" }`

I get a 404. Did I miss something?

**Comment by bploetz** [comment] 2015-09-30 16:27
Huh, weird. I took a quick peek at the specs and I don't see a test for this case, so could very well be a bug.

**Comment by bploetz** [comment] 2015-09-30 16:41
I can't reproduce this in a test Rails 4.1 app.

config/routes.rb:
```ruby
    api_version(module: 'V01', path: {value: 'v0.1'}, header: {name: "Accept", value: "application/vnd.url.com; version=0.1"}, default: true, defaults: {format: :json}) do
      resources :foos
    end
```

app/controllers/v01/foos_controller.rb:
```ruby
class V01::FoosController < V01::BaseController
  def index
    render :text => "hi"
  end
end
```

Requests:
```
> curl http://localhost:3000/foos
hi
> curl http://localhost:3000/v0.1/foos
hi
> curl -H "Accept: application/vnd.url.com; version=0.1" http://localhost:3000/v0.1/foos
hi
```

@johnrees what version of Rails are you using? Are you passing anything else in the `Accept` header besides the version string when you make the request that results in a 404?

**Comment by bploetz** [comment] 2016-07-08 19:09
Closing due to radio silence. Re-open if @johnrees gets back to us on this one.

**Closed by bploetz** 2016-07-08 19:09 UTC
